# Generated by Django 3.2 on 2021-04-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submited_Samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ssn', models.CharField(max_length=100)),
                ('result', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
