# Generated by Django 3.2 on 2021-04-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submited_Samples',
            new_name='Sample',
        ),
    ]
