# Generated by Django 3.2 on 2021-04-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_rename_submited_samples_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
