# Generated by Django 3.2 on 2021-04-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='ssn',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
