# Generated by Django 3.2 on 2021-04-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20210420_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='frekvens',
            field=models.CharField(default='Okänd', max_length=150),
        ),
        migrations.AddField(
            model_name='patient',
            name='gata',
            field=models.CharField(default='Okänd', max_length=150),
        ),
        migrations.AddField(
            model_name='patient',
            name='mail',
            field=models.CharField(default='Okänd', max_length=150),
        ),
        migrations.AddField(
            model_name='patient',
            name='postort',
            field=models.CharField(default='Okänd', max_length=150),
        ),
        migrations.AddField(
            model_name='patient',
            name='telefon',
            field=models.CharField(default='Okänd', max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(default='Okänd', max_length=150),
        ),
    ]
