# Generated by Django 3.2 on 2021-04-21 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='opdate',
        ),
        migrations.AddField(
            model_name='patient',
            name='operationsdatum',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
