# Generated by Django 3.2 on 2021-05-03 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0002_auto_20210421_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='kallelsedatum',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
