# Generated by Django 3.2 on 2021-05-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0002_alter_hantera_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provsvar',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
