# Generated by Django 3.2 on 2021-05-17 10:58

from django.db import migrations, models
import psa.models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0003_alter_provsvar_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hantera',
            name='ssn',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, validators=[psa.models.validate_ssn]),
        ),
    ]
