# Generated by Django 3.2 on 2021-05-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0003_patient_kallelsedatum'),
    ]

    operations = [
        migrations.AddField(
            model_name='provsvar',
            name='done',
            field=models.CharField(default='False', max_length=100),
        ),
    ]
