# Generated by Django 3.2.1 on 2021-05-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0003_patient_kallelsedatum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hantera',
            fields=[
                ('ssn', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('result', models.CharField(max_length=150)),
            ],
        ),
    ]
