# Generated by Django 3.2 on 2021-05-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0004_hantera'),
        ('psa', '0004_provsvar_done'),
    ]

    operations = [
    ]
