# Generated by Django 3.2 on 2021-05-11 19:38

from django.db import migrations, models
import django.db.models.deletion
import psa.models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0005_merge_0004_hantera_0004_provsvar_done'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kallelse',
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name_plural': 'Patienter'},
        ),
        migrations.AlterModelOptions(
            name='provsvar',
            options={'verbose_name_plural': 'Provsvar'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='gata',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mail',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='namn',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='postnr',
            field=models.IntegerField(validators=[psa.models.validate_postnr]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='postort',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ssn',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, validators=[psa.models.validate_ssn]),
        ),
        migrations.AlterField(
            model_name='provsvar',
            name='ssn',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='psa.patient', validators=[psa.models.validate_ssn, psa.models.read_from_db], verbose_name='Kopplad patient'),
        ),
    ]
